/-
# Perron Stress Pricing: Residual Tilts and Price Intervals

Formalization of Theorem 3.3 (bounded local residual tilts),
Theorem 4.2 (explicit residual price interval), and
Theorem 4.5 (Perron stress pricing decomposition) from:
  "Perron Stress Pricing under Public Compression"
  by J. Vidal Llauradó (2026)
-/
import Mathlib
import RequestProject.PerronStress.Defs
import RequestProject.PerronStress.PublicEquivalence

open MeasureTheory MeasurableSpace Filter
open scoped ENNReal NNReal BigOperators

noncomputable section

variable {Ω : Type*} {m₀ : MeasurableSpace Ω} {μ : Measure Ω}
variable [IsFiniteMeasure μ]

namespace PerronStress

/-! ## Theorem 3.3: Bounded local residual tilts -/

/-
Theorem 3.3 (conditional expectation of tilt):
If `E_Q[R | H] = 0` then `E_Q[1 + η R | H] = 1` a.e.
-/
theorem condExp_localTilt_eq_one
    (S : Setup Ω m₀ μ)
    (R : Ω → ℝ)
    (hR_resid : IsPublicResidual S R)
    (hR_int : Integrable R μ)
    (η : ℝ) :
    μ[localTilt η R | S.mH] =ᵐ[μ] fun _ => (1 : ℝ) := by
  have hTilt : μ[(fun _ => (1 : ℝ)) + η • R | S.mH] =ᵐ[μ] μ[(fun _ => (1 : ℝ)) | S.mH] + η • μ[R | S.mH] := by
    have hTilt : μ[(fun _ => (1 : ℝ)) + η • R | S.mH] =ᵐ[μ] μ[(fun _ => (1 : ℝ)) | S.mH] + μ[η • R | S.mH] := by
      apply_rules [ MeasureTheory.condExp_add ];
      · exact MeasureTheory.integrable_const _;
      · exact hR_int.const_mul η;
    refine' hTilt.trans _;
    apply_rules [ Filter.EventuallyEq.add, MeasureTheory.condExp_smul ];
    rfl;
  refine' hTilt.trans _;
  rw [ MeasureTheory.condExp_const ];
  · filter_upwards [ hR_resid ] with ω hω using by simp +decide [ hω ] ;
  · exact le_trans S.hHG ( le_trans S.hGK S.hK0 )

/-
Theorem 3.3 (positivity of tilt):
If `|η| · ‖R‖_∞ < 1` then `1 + η R > 0` a.e.
-/
theorem localTilt_pos
    (R : Ω → ℝ)
    (η : ℝ)
    (hR_bdd : ∃ C : ℝ, ∀ ω, |R ω| ≤ C)
    (hη : ∀ C : ℝ, (∀ ω, |R ω| ≤ C) → |η| * C < 1) :
    ∀ ω, 0 < localTilt η R ω := by
  -- For each ω, |η * R(ω)| ≤ |η| * |R(ω)| ≤ |η| * C < 1 by the hypothesis hη applied to C from hR_bdd.
  have h_bound : ∀ ω, |η * R ω| ≤ |η| * hR_bdd.choose := by
    exact fun ω => by rw [ abs_mul ] ; exact mul_le_mul_of_nonneg_left ( hR_bdd.choose_spec ω ) ( abs_nonneg _ ) ;
  exact fun ω => show 0 < 1 + η * R ω from by nlinarith [ abs_lt.mp ( lt_of_le_of_lt ( h_bound ω ) ( hη _ hR_bdd.choose_spec ) ) ] ;

/-
Theorem 3.3 (affine pricing identity):
    `E_{Q_η}[X] = E_Q[X] + η · E_Q[X · R]`.
-/
theorem localTilt_pricing
    (X R : Ω → ℝ)
    (η : ℝ)
    (hX_int : Integrable X μ)
    (hR_int : Integrable R μ)
    (hXR_int : Integrable (fun ω => X ω * R ω) μ)
    (_hLT_int : Integrable (fun ω => localTilt η R ω * X ω) μ) :
    ∫ ω, localTilt η R ω * X ω ∂μ = ∫ ω, X ω ∂μ + η * ∫ ω, X ω * R ω ∂μ := by
  rw [ ← MeasureTheory.integral_const_mul ];
  rw [ ← MeasureTheory.integral_add ] ; congr ; ext ω ; unfold localTilt ; ring;
  · exact hX_int;
  · exact hXR_int.const_mul η

/-! ## Theorem 4.2: Explicit residual price interval

The price interval generated by a bounded residual direction `R`
with tilt parameter bound `η̄` is:

  Π⁻(X) = E[X] - η̄ |E[XR]|
  Π⁺(X) = E[X] + η̄ |E[XR]|
-/

/-
Theorem 4.2 (price interval lower bound):
    `inf_{|η| ≤ η̄} E_{Q_η}[X] = E[X] - η̄ |E[XR]|`.
-/
omit [IsFiniteMeasure μ] in
theorem price_interval_lower
    (X R : Ω → ℝ) (η_bar : ℝ) (hη_pos : 0 ≤ η_bar)
    (_hX_int : Integrable X μ)
    (_hR_int : Integrable R μ)
    (_hXR_int : Integrable (fun ω => X ω * R ω) μ) :
    IsGLB {∫ ω, X ω ∂μ + η * ∫ ω, X ω * R ω ∂μ | η ∈ Set.Icc (-η_bar) η_bar}
      (∫ ω, X ω ∂μ - η_bar * |∫ ω, X ω * R ω ∂μ|) := by
  constructor;
  · rintro _ ⟨ η, ⟨ hη₁, hη₂ ⟩, rfl ⟩;
    cases abs_cases ( ∫ ω, X ω * R ω ∂μ ) <;> nlinarith;
  · rintro x hx;
    cases abs_cases ( ∫ ω, X ω * R ω ∂μ ) <;> simp +decide [ * ];
    · exact hx ⟨ -η_bar, ⟨ by linarith, by linarith ⟩, by ring ⟩;
    · exact hx ⟨ η_bar, ⟨ by linarith, by linarith ⟩, rfl ⟩

/-
Theorem 4.2 (price interval upper bound):
    `sup_{|η| ≤ η̄} E_{Q_η}[X] = E[X] + η̄ |E[XR]|`.
-/
omit [IsFiniteMeasure μ] in
theorem price_interval_upper
    (X R : Ω → ℝ) (η_bar : ℝ) (hη_pos : 0 ≤ η_bar)
    (_hX_int : Integrable X μ)
    (_hR_int : Integrable R μ)
    (_hXR_int : Integrable (fun ω => X ω * R ω) μ) :
    IsLUB {∫ ω, X ω ∂μ + η * ∫ ω, X ω * R ω ∂μ | η ∈ Set.Icc (-η_bar) η_bar}
      (∫ ω, X ω ∂μ + η_bar * |∫ ω, X ω * R ω ∂μ|) := by
  constructor;
  · rintro _ ⟨ η, ⟨ hη₁, hη₂ ⟩, rfl ⟩ ; cases abs_cases ( ∫ ω, X ω * R ω ∂μ ) <;> nlinarith;
  · rintro x hx;
    cases abs_cases ( ∫ ω, X ω * R ω ∂μ ) <;> simp +decide [ * ];
    · exact hx ⟨ η_bar, ⟨ by linarith, by linarith ⟩, rfl ⟩;
    · nlinarith [ hx ⟨ -η_bar, ⟨ by linarith, by linarith ⟩, rfl ⟩ ]

/-! ## Theorem 4.5: Perron stress pricing decomposition -/

/-
Theorem 4.5 (pricing decomposition):
    `E_{Q_η}[X] = Π₀(X) + Π_R^res(X; η)`.

Since `E_{Q_η}[X] = E[X] + η E[XR]` and the residual term
`η ⟨L_X - E[L_X|H], R⟩` equals `η E[XR]` when `R` is K-measurable
and `E[R|H] = 0`, this decomposes into baseline price plus residual.
-/
theorem pricing_decomposition
    (S : Setup Ω m₀ μ)
    (X R : Ω → ℝ)
    (η : ℝ)
    (hR_Kmeas : @StronglyMeasurable Ω ℝ _ S.mK R)
    (hR_resid : IsPublicResidual S R)
    (hX_int : Integrable X μ)
    (hR_int : Integrable R μ)
    (hXR_int : Integrable (fun ω => X ω * R ω) μ)
    (hLR_int : Integrable (fun ω => latentLoading S X ω * R ω) μ)
    (hPSR_int : Integrable (fun ω => publicShadow S X ω * R ω) μ)
    (hLT_int : Integrable (fun ω => localTilt η R ω * X ω) μ) :
    ∫ ω, localTilt η R ω * X ω ∂μ =
      baselinePrice μ X + residualPrice S X R η := by
  -- Apply the linearity of the integral.
  have h_integral : ∫ ω, (latentLoading S X ω - publicShadow S X ω) * R ω ∂μ = ∫ ω, latentLoading S X ω * R ω ∂μ - ∫ ω, publicShadow S X ω * R ω ∂μ := by
    simpa only [ sub_mul ] using MeasureTheory.integral_sub hLR_int hPSR_int;
  -- By definition of latentLoading and publicShadow, we can rewrite the integrals.
  have hLatentLoading : ∫ ω, latentLoading S X ω * R ω ∂μ = ∫ ω, X ω * R ω ∂μ := by
    -- By definition of conditional expectation, we have:
    have h_cond_exp : ∫ ω, (latentLoading S X ω) * R ω ∂μ = ∫ ω, (X ω) * R ω ∂μ := by
      have h_cond_exp_def : ∀ᵐ ω ∂μ, (latentLoading S X ω) = (μ[X | S.mK]) ω := by
        exact Filter.Eventually.of_forall fun ω => rfl
      rw [ MeasureTheory.integral_congr_ae ( h_cond_exp_def.mono fun ω hω => by rw [ hω ] ) ];
      have h_cond_exp_def : ∀ᵐ ω ∂μ, (μ[X * R | S.mK]) ω = (μ[X | S.mK]) ω * R ω := by
        apply_rules [ MeasureTheory.condExp_mul_of_stronglyMeasurable_right ];
      rw [ ← MeasureTheory.integral_congr_ae h_cond_exp_def, MeasureTheory.integral_condExp ];
      · rfl;
      · exact S.hK0;
    exact h_cond_exp
  have hPublicShadow : ∫ ω, publicShadow S X ω * R ω ∂μ = 0 := by
    have hPublicShadow : μ[publicShadow S X * R | S.mH] =ᵐ[μ] 0 := by
      have hPublicShadow : μ[publicShadow S X * R | S.mH] =ᵐ[μ] publicShadow S X * μ[R | S.mH] := by
        apply_rules [ MeasureTheory.condExp_mul_of_stronglyMeasurable_left ];
        exact MeasureTheory.StronglyMeasurable.mono ( MeasureTheory.stronglyMeasurable_condExp ) ( by aesop );
      filter_upwards [ hPublicShadow, hR_resid ] with ω hω₁ hω₂ using by aesop;
    have hPublicShadow : ∫ ω, publicShadow S X ω * R ω ∂μ = ∫ ω, μ[publicShadow S X * R | S.mH] ω ∂μ := by
      rw [ MeasureTheory.integral_condExp ];
      · rfl;
      · exact le_trans S.hHG ( le_trans S.hGK S.hK0 );
    rw [ hPublicShadow, MeasureTheory.integral_eq_zero_of_ae ‹_› ];
  unfold localTilt residualPrice baselinePrice;
  simp_all +decide [ add_mul, mul_assoc ];
  rw [ MeasureTheory.integral_add, MeasureTheory.integral_const_mul ];
  · simp +decide only [mul_comm];
  · exact hX_int;
  · simpa only [ mul_comm ] using hXR_int.const_mul η

end PerronStress

end